FROM node:23-slim

ARG SERVER_HOST
ENV NEXT_PUBLIC_SERVER_HOST=${SERVER_HOST}

ARG SPOTIFY_APP_ID
ENV NEXT_PUBLIC_SPOTIFY_APP_ID=${SPOTIFY_APP_ID}

ENV NEXT_SHARP_PATH=/app/node_modules/sharp

WORKDIR /app

COPY ./package.json .
RUN yarn
COPY ./tsconfig.json .
COPY ./postcss.config.js .
COPY ./next.config.mjs .
COPY ./tailwind.config.ts .
RUN mkdir public
COPY ./public/* public/

CMD ["yarn", "dev", "-p", "${CLIENT_PORT}"]
