networks:
  internal:
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: playlist
      POSTGRES_DB: playlist
      POSTGRES_PASSWORD: password
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - internal
  server:
    restart: always
    depends_on:
      - db
    build:
      context: server
      dockerfile: Dockerfile.dev
      args:
        SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPOTIFY_APP_ID: ${SPOTIFY_APP_ID}
      SPOTIFY_SECRET_FILE: /run/secrets/spotify_secret
      SPOTIFY_REDIRECT: http://localhost:${CLIENT_PORT}/spotify
      DB_HOST: db
      DB_USER: playlist
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: playlist
      SECRET_KEY_FILE: /run/secrets/secret_key
      CLIENT_HOST: "localhost:${CLIENT_PORT}"
    volumes:
      - ./server/src:/app/src
    secrets:
      - spotify_secret
      - secret_key
    networks:
      - internal
  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
      args:
        SPOTIFY_APP_ID: ${SPOTIFY_APP_ID}
        SERVER_HOST: localhost:${SERVER_PORT}
        CLIENT_PORT: ${CLIENT_PORT}
        SERVER_PROTOCOL: http
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_APP_ID}
      CLIENT_PORT: ${CLIENT_PORT}
    depends_on:
      - server
    volumes:
      - ./client/src:/app/src
    networks:
      - internal
secrets:
  secret_key:
    file: key.secret
  spotify_secret:
    file: spotify.secret
volumes:
  pgdata:
