FROM node:23-slim

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app
COPY package*.json ./
COPY tsconfig.json ./

USER node

RUN yarn
COPY --chown=node:node . .

CMD [ "node", "--experimental-transform-types", "src/index.ts"]