name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild the docker image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd ${{ vars.PROJECT_ROOT }}
            git pull
            docker compose -f docker-compose.prod.yml up --build -d
            source .env
            chmod +x ./db/run.sh
            ./db/run.sh ./db/data/ $DB_NAME $DB_PORT $DB_USER $DB_NAME
            rm ./db/data/*
            git add ./db/data
            git commit -m "tidy: remove completed db scripts"
            git push
